Enum CuisineType {
  Italian
  Indian
  Chinese
  Japanese
  Mexican
  American
  French
  Other
}

Enum MeasurementUnit {
  gram
  kilogram
  millilitre
  litre
  tsp
  tbsp
  cup
  piece
}

Enum DietaryChoice {
  Vegan
  Vegetarian
  Pescatarian
  Halal
  Kosher
  GlutenFree
  DairyFree
}

Table Restaurant {
  id int [pk, increment]
  restaurant_name varchar(255)
  longitude varchar(50)
  latitude varchar(50)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table RestaurantCuisine {
  id int [pk, increment]
  restaurant_id int [ref: > Restaurant.id]
  cuisine CuisineType

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table Recipe {
  id int [pk, increment]
  restaurant_id int [ref: > Restaurant.id]

  recipe_name varchar(255)
  description longtext
  recipe_originator varchar(255)
  avg_restaurant_price decimal(10,2)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table RecipeMetadata {
  id int [pk, increment]
  recipe_id int [ref: > Recipe.id]

  metadata_name varchar(100)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table RecipeItem {
  id int [pk, increment]
  recipe_id int [ref: > Recipe.id]

  menu_item_name varchar(255)
  cost decimal(10,2)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table RecipeFoodItems {
  id int [pk, increment]

  recipe_id int [ref: > Recipe.id]
  food_item_id int [ref: > FoodItems.id]

  measurement_unit MeasurementUnit
  measurement_quantity int
  measurement_text varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table Images {
  id int [pk, increment]
  url varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table FoodItems {
  id int [pk, increment]

  image_id int [ref: > Images.id]
  fridge_id int [ref: > Fridge.id]

  ingredient_name varchar(255)
  available boolean

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table GroceryStore {
  id int [pk, increment]

  store_name varchar(255)
  longitude varchar(50)
  latitude varchar(50)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table GroceryStoreInventory {
  id int [pk, increment]

  grocery_store_id int [ref: > GroceryStore.id]
  food_item_id int [ref: > FoodItems.id]

  price decimal(10,2)

  measurement_unit MeasurementUnit
  measurement_quantity int
  measurement_text varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table Users {
  id int [pk, increment]

  name varchar(255)
  longitude varchar(50)
  latitude varchar(50)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table Fridge {
  id int [pk, increment]

  user_id int [ref: > Users.id]
  fridge_name varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table PreparationSteps {
  id int [pk, increment]

  recipe_id int [ref: > Recipe.id]
  recipe_step varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table PreparationStepsProgress {
  id int [pk, increment]

  preparation_step_id int [ref: > PreparationSteps.id]

  total_steps int
  current_step int

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table SavedRecipes {
  id int [pk, increment]

  recipe_id int [ref: > Recipe.id]
  user_id int [ref: > Users.id]

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table DietaryPreferences {
  id int [pk, increment]

  user_id int [ref: > Users.id]
  dietary_choice DietaryChoice

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table Video {
  id int [pk, increment]

  url varchar(255)

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}
